version: '3.8'

services:
  ros2_dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./Driver-ROS2-MTS-Test-main:/home/ros/ros2_ws
    environment:
      - DEBIAN_FRONTEND=noninteractive
    tty: true

  # ros2_full:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: full
  #   volumes:
  #     - lol:/home/ros/ros2_ws
  #   environment:
  #     - DEBIAN_FRONTEND=noninteractive
  #   tty: true

  # ros2_gazebo:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: gazebo
  #   volumes:
  #     - lol:/home/ros/ros2_ws
  #   environment:
  #     - DEBIAN_FRONTEND=noninteractive
  #   tty: true

volumes:
  lol:
