name: ros2
services:
  ros2_dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./Driver-ROS2-MTS-Test-main:/home/ros/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix 
      - /tmp/.XAuthority:/tmp/.XAuthority 
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - DISPLAY=$DISPLAY
      - XAUTHORITY=/tmp/.XAuthority
    tty: true